spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:aggregator;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver



logging:
    level:
        org:
            springframework: ERROR
