CREATE TABLE BANKS (
  bank_id INT SERIAL NOT NULL,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (bank_id)
);

ALTER TABLE BANKS
  ADD UNIQUE (name);

CREATE TABLE CURRENCIES (
  bank_id INT NOT NULL,
  name VARCHAR(15) NOT NULL,
  buy_rate FLOAT DEFAULT 0,
  sell_rate FLOAT DEFAULT 0,
  PRIMARY KEY (bank_id, name),
);

ALTER TABLE CURRENCIES
    ADD FOREIGN KEY (bank_id) REFERENCES BANKS (bank_id) ON UPDATE NO ACTION ON DELETE CASCADE

